### ISSUE TITLE
Schedule a content meeting

### ISSUE THREAD

**Issue by arthurvr** [jquery/meetings.jquery.org#16]
We stopped doing meetings for `jquery-content` a while ago, but as discussed in `#jquery-content` here and there, it would be good to pick them up again. ([here](http://irc.jquery.org/%23jquery-content/default_%23jquery-content_20141223.log.html#t08:06:52) and [there](http://irc.jquery.org/%23jquery-content/latest.log.html#t08:55:39))
 
I just wanted to open this issue to get the ball rolling again. Would you guys like to have them again? When would these best fit?

I guess a meeting every 2 weeks is more handy for some of us?

Currently on our agenda [one is planned](https://www.google.com/calendar/render?eid=Njhkb3NvZ2JtY3RwYXBpdXRmZGtqMWVjdW9fMjAxNTAxMDFUMTgwMDAwWiBqcXVlcnkuY29tX3VjdnUyNzNkNGFlMGhsMWpsb2M2MHRoMXRvQGc&ctz=America/New_York&sf=true&output=xml#f) for every week, but since we don't do them anymore it's maybe a good idea to revisit the timing. Back then they were weekly and Thursdays 1pm ET.

Going to ping the frequent contributors to `jquery-content` repos in here, feel free to ping in others since I'il forget people surely.

--------------------------

_@agcolom @ajpiano @gnarf @scottgonzalez @RedWolves @dmethvin @kborchers @jzaefferer @gseguin @nacin @connor @danheberden @addyosmani @bobholt @rdworth @rmurphey @jaspermdegroot @rdworth_

**Comment by jzaefferer** [comment]
Looking at the learn repo PRs, @AurelioDeRosa should also be invited.

**Comment by AurelioDeRosa** [comment]
Thank you for the mention @jzaefferer. If everyone agrees, now that I'm back from holidays I'd love to be involved.

**Comment by arschmitz** [comment]
@AurelioDeRosa any help is always appreciated, and I know I see your name fly by on issues very often. So if your available and interested, I agree with @jzaefferer you should probably be there.

**Comment by agcolom** [comment]
The content meetings will take place on Wednesdays 1pm ET, every 2 weeks, starting January 14th (alternate weeks from Dev Leads meeting).
Closing this issue as now resolved.
@scottgonzalez Who is the best person to ask to add this to the Calendar? (And remove the old content meeting slot?). I don't think I have access. Thanks.

**Comment by scottgonzalez** [comment]
@agcolom I've never had much luck logging into other Google accounts (I always seem to get stuck in infinite login redirects). I've pinged a few people so someone should get back to you.

**Comment by agcolom** [comment]
@scottgonzalez Thanks. I'll try to make the edits as soon as I get access.

**Comment by dmethvin** [comment]
I *think* I got it set up right, on the third try.

**Comment by arthurvr** [comment]
@dmethvin looks fine.

**Comment by agcolom** [comment]
Agenda at https://docs.google.com/spreadsheets/d/1pJhQj3Nn-5rdmqocN9NKP8CpnC4Z42TRAvNC3SJLj3o/edit#gid=0
