### ISSUE TITLE
Rename categories to not be so jQuery specific

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/meetings.jquery.org#20]
As the foundation grows, categories like "core", "ui", and "mobile" are now too vague. We should rename them to include the full project names.

**Comment by arthurvr** [comment]
:+1: Although we might want to setup redirects if we're going to update the folder names as well.

**Comment by agcolom** [comment]
@scottgonzalez should we just change the name in https://github.com/jquery/meetings.jquery.org/blob/master/taxonomies.js or should we rename the folders as well? If we rename the folders, what syntax do we use? I'd be happy with changing just the name but not sure whether that would be ok or back practice.

**Comment by scottgonzalez** [comment]
The taxonomies are the most important since they affect the site. Renaming the folders would be ideal, but it's not as important.

**Comment by agcolom** [comment]
@scottgonzalez great, thanks, so I'll submit a PR (probably tomorrow) with the name changes and take it from there.

**Comment by arthurvr** [comment]
Thanks @agcolom!
