### ISSUE TITLE
PrivateInternetAccess link of the IRC iframe doesn't work

### ISSUE THREAD

**Issue by AurelioDeRosa** [jquery/meetings.jquery.org#21]
In the `iframe` for the IRC chat we have a link that points to PrivateInternetAccess. However, on click of the link this is what Chrome/Opera shows:

![meetings-issue](https://cloud.githubusercontent.com/assets/1430979/8020008/221afd4e-0c61-11e5-802f-27e566642009.png)

Firefox tries to load something but for the user the only result is that it removes every element of the `iframe`.

Internet Explorer shows the following error:

![meetings-issue-ie](https://cloud.githubusercontent.com/assets/1430979/8020014/82c67934-0c61-11e5-8b5d-a41a4124e4cc.png)

**Comment by arthurvr** [comment]
Good catch @AurelioDeRosa. Wondering if there's something we can do about this.

**Comment by agcolom** [comment]
I may be completely wrong but adding the target="_blank" to the link seems to fix this?
