### ISSUE TITLE
Are the meetings recorded and why not make those public?

### ISSUE THREAD

**Issue by whyAmIseeay** [jquery/meetings.jquery.org#24]
It catched my eye that the "Executive Committee", "Dev Leads" and "jQuery events" meetings are all being held in private. Why? Doesn't sound open source alike. Maybe take a similar approach as the io.js team and record them and put online?

I wonder how interesting the EC is (and maybe that actually contains info better held private) but things like dev leads meetings sound interesting if people want to know what's up and where the very smart people here are up to.

**Comment by kborchers** [comment]
So the Executive Committee and Events meetings are private for reasons of discussing budgets, and other internal matters that are usually made public eventually (via tax reporting, etc.) but can't be public at that moment. The Dev Leads meeting is an optional meeting where any project leads that want to meet and give a status update can. For the most part though, this information is available via the individual team meetings which are public. The Foundation has no control over this meeting and it is up to the leads if they want it to be public or private or if they even have this meeting.

**Comment by rxaviers** [comment]
@whyAmIseeay although, I believe you have a very good point.

@kborchers, although Executive Committee, Dev Leads, and Events meetings are held private today, could the minutes be made public by removing any sensitive data (like budget numbers)? This could be at least a start to foster openness.

**Comment by kborchers** [comment]
The board can chime in here if they want but my view is this:

Dev Leads - They can do what ever they want with that meeting though like I said, I'm not sure what useful info comes from that meeting beyond the info that was already public from the team meetings
Events - Everything that can be public is made public as soon as it can be via the event website or at the event so there would likely be nothing to report
EC - Again, the items discussed here are made public when they can be, if they ever can be, so I do not see those being made public.

**Comment by scottgonzalez** [comment]
FWIW, the dev leads minutes actually should be public via the mailing list, but the proper mailing list was never created.

**Comment by gnarf** [comment]
> FWIW, the dev leads minutes actually should be public via the mailing list, but the proper mailing list was never created.

Should we just log the meeting minutes here instead?

**Comment by gnarf** [comment]
I've opened up #27 to handle publishing the dev leads meeting minutes.

If I understand @kborchers' earlier comments, I think we can close this issue and let #27 take it's course. Neither the EC or Events meetings could be made public (for reasons previously mentioned)

Feel free to reopen if you think I missed something, and thanks much @whyAmIseeay for bringing this issue to our attention.  :heart_eyes:
