### ISSUE TITLE
"I'm not a robot" link not working correctly

### ISSUE THREAD

**Issue by SaptakS** [jquery/meetings.jquery.org#25]
On clicking the checkbox for captcha, the grid of images that open are not scrollable and hence the question is not visible.
![screenshot from 2015-10-05 22 54 01](https://cloud.githubusercontent.com/assets/9530293/10287975/c4c4765e-6bb3-11e5-9c67-896bb57d55da.png)
on reloading, the problem persists. The iframe is not scrollable.

**Comment by SaptakS** [comment]
It seems that the irc link loaded in iframe, the overflow in that page is hidden.

**Comment by scottgonzalez** [comment]
We should probably just remove the iframe and link to the page instead.

**Comment by SaptakS** [comment]
Yes. That is a good idea. Because I can't see any other way how we can make the overflow of the  content loaded by iframe scrollable.

**Comment by SaptakS** [comment]
Should I make that change and send a pull request?

**Comment by arthurvr** [comment]
> Should I make that change and send a pull request?

SGTM. That would also fix https://github.com/jquery/meetings.jquery.org/issues/21.

**Comment by SaptakS** [comment]
Yeah. I actually got this issue while seeing that issue. So should I modify it or is there a better option?

**Comment by arthurvr** [comment]
I think we should just remove the iframe, add a simple link to the webchat and call both issues fixed. The tiny iframe wasn't really handy anyways.

**Comment by SaptakS** [comment]
OK. I will make the change and send a PR
