### ISSUE TITLE
Create section for Developer Leads meetings notes

### ISSUE THREAD

**Issue by gnarf** [jquery/meetings.jquery.org#27]
Attempting to solve for 1 of the 3 meetings mentioned in #24.

We've discussed this a bit on the mailing list, but I'd like to put this issue up to document our intent to publish these ASAP (we can probably even go back a bit in history and publish as well).

Unless there are any objections:

* [x] Add a http://meetings.jquery.org/category/devleads/ (thoughts on a better slug?)
* [x] Add link in the sidebar in the template for http://meetings.jquery.org/
* [ ] Collect back-dated minutes from the mailing list and post.

**Comment by jzaefferer** [comment]
Let's! The dev leads meeting is generally more abstract, roadmappy, which is good to follow projects that you're otherwise not much involved in.

**Comment by scottgonzalez** [comment]
http://meetings.jquery.org/category/project-leads/

Thanks @agcolom!

**Comment by scottgonzalez** [comment]
@agcolom will go through the old minutes and post them as well, but we'll close this now.

**Comment by gnarf** [comment]
:heart_eyes: @agcolom :kissing_heart:

**Comment by agcolom** [comment]
:-)

**Comment by rxaviers** [comment]
:clap:
